 terraform_force_deployment:
    name: Force New Deployment with Terraform
    needs: [docker_build_push, ecr_creation]
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Taint ECS service for force new deployment
      #working-directory: ecs
      run: |
        terraform init
        terraform taint aws_ecs_service.priya-ecs2-service
        terraform apply -auto-approve